### ISSUE TITLE
Error "javax/xml/bind/DatatypeConverter" to obtain the token

### ISSUE THREAD

**Issue by erobertolima121** [sebascastillo89/jwtDemo#3]
Resolving a problem found:

When calling **"user"** to obtain the token, error **"javax/xml/bind/DatatypeConverter"** is returned.

This problem is solved by adding the following dependencies to pom.xml (using java 9 or later)

	
	<dependency>
		<groupId>jakarta.xml.bind</groupId>
		<artifactId>jakarta.xml.bind-api</artifactId>
		<version>2.3.2</version>
	</dependency>
	
	<dependency>
		<groupId>org.glassfish.jaxb</groupId>
		<artifactId>jaxb-runtime</artifactId>
		<version>2.3.2</version>
	</dependency>
@sebascastillo89, if you want to close this problem feel free, I hope I helped.

Cheers.

**Comment by sebascastillo89** [comment]
Thank you so much for your help!
I just add these dependencies in pom file
